<?php

/**
 * @file
 * Module hooks and functions for the Tableau WorldServer Integration module.
 */

use TableauWorldServer\MiddleWare;
use TableauWorldServer\Querier;


/**
 * Implements hook_menu().
 */
function tableau_worldserver_integration_menu() {
  return array(
    'admin/config/services/world-server' => array(
      'title' => 'WorldServer Integration',
      'description' => 'Configure SFTP credentials and other goodies for connecting with WorldServer.',
      'type' => MENU_NORMAL_ITEM,
      'file' => 'inc/admin.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('tableau_worldserver_integration_settings'),
      'access arguments' => array('administer entity xliff'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tableau_worldserver_integration_form_entity_xliff_actions_alter(&$form, &$form_state) {
  module_load_include('inc', 'tableau_worldserver_integration', 'inc/admin');
  _tableau_worldserver_integration_form_entity_xliff_actions_alter($form, $form_state);
}

/**
 * Returns an authenticated phpseclib SFTP client or NULL on failure.
 *
 * @return Net_SFTP|null
 *   An authenticated Net_SFTP instance or NULL on failure.
 */
function tableau_worldserver_integration_sftp_client() {
  $client = &drupal_static(__FUNCTION__, FALSE);

  if ($client === FALSE) {
    $host = variable_get('tableau_worldserver_integration_sftp_host', FALSE);
    $un = variable_get('tableau_worldserver_integration_sftp_un', FALSE);
    $pw = variable_get('tableau_worldserver_integration_sftp_pw', FALSE);

    if ($host && $un && $pw) {
      $client = new Net_SFTP($host);
      if (!$client->login($un, $pw)) {
        $client = NULL;
      }
    }
    else {
      $client = NULL;
    }
  }

  return $client;
}

/**
 * Returns an instance of our MiddleWare class for a given entity. The same
 * MiddleWare instance will be returned throughout the request lifecycle.
 *
 * @param \EntityDrupalWrapper $wrapper
 * @return MiddleWare|bool
 */
function tableau_worldserver_integration_get_middleware(\EntityDrupalWrapper $wrapper) {
  $middleware = &drupal_static(__FUNCTION__, array());
  $key = $wrapper->type() . ':' . $wrapper->getIdentifier();

  if (!array_key_exists($key, $middleware)) {
    if ($client = tableau_worldserver_integration_sftp_client()) {
      $middleware[$key] = new MiddleWare($client, $wrapper);
    }
    else {
      $middleware[$key] = FALSE;
    }
  }

  return $middleware[$key];
}

/**
 * Returns a list of content that has been translated in WorldServer that is
 * ready for processing in Drupal.
 *
 * @param object[] $langs
 *   (optional) An associative array of Drupal language objects, keyed by
 *   language. If nothing is provided, all installed languages will be assumed.
 *
 * @return array
 *   A multidimensional array of the following form:
 *   - [drupal_language]: The Drupal language identifier.
 *     - [entity_type]: An array of entity IDs to be processed, keyed by the
 *       type of entity.
 */
function tableau_worldserver_integration_get_processable(array $langs = array()) {
  $response = array();
  if ($client = tableau_worldserver_integration_sftp_client()) {
    $query = new Querier($client);
    $response = $query->getProcessableByEntity($langs);
  }
  return $response;
}

/**
 * Generates XLIFFs for the specified entity in the specified languages, then
 * pushes those files up to WorldServer.
 *
 * @param string $type
 *   The type of entity.
 *
 * @param mixed $entity
 *   The entity (or entity ID) to push.
 *
 * @param object[] $langs
 *   (optional) An associative array of Drupal language objects, keyed by
 *   language. If nothing is provided, all installed languages will be assumed.
 */
function tableau_worldserver_integration_put_entity_xliffs($type, $entity, $langs = array()) {
  $wrapper = entity_metadata_wrapper($type, $entity);
  if ($middleware = tableau_worldserver_integration_get_middleware($wrapper)) {
    // Get the middleware provider and push up configured files.
    $middleware->putXliffs($langs);
  }
}

/**
 * Loads translated/processed XLIFF data from Worldserver, unserializes the
 * data against the wrapped entity, and saves all relevant entities.
 *
 * @param string $type
 *   The type of entity.
 *
 * @param mixed $entity
 *   The entity (or entity ID) to push.
 *
 * @param object[] $langs
 *   (optional) An associative array of Drupal language objects, keyed by
 *   language. If nothing is provided, all installed languages will be assumed.
 */
function tableau_worldserver_integration_set_entity_xliffs($type, $entity, $langs = array()) {
  $wrapper = entity_metadata_wrapper($type, $entity);
  if ($middleware = tableau_worldserver_integration_get_middleware($wrapper)) {
    $middleware->setXliffs($langs);
  }
}
