<?php

/**
 * @file
 * Install and update hooks for the Tableau WorldServer Integration module.
 */


/**
 * Implements hook_install().
 */
function tableau_worldserver_integration_install() {
  // Initialize the file prefix with a unique enough value.
  $uniqueEnough = uniqid('drupal-');
  variable_set('tableau_worldserver_integration_file_prefix', $uniqueEnough);
}

/**
 * Implements hook_uninstall().
 */
function tableau_worldserver_integration_uninstall() {
  $vars = array(
    'tableau_worldserver_integration_sftp_host',
    'tableau_worldserver_integration_sftp_un',
    'tableau_worldserver_integration_sftp_pw',
    'tableau_worldserver_integration_target_root',
    'tableau_worldserver_integration_source_root',
    'tableau_worldserver_integration_last_processed',
    'tableau_worldserver_integration_file_prefix',
  );

  foreach ($vars as $var) {
    variable_del($var);
  }
}
